services:
  # client service
  client:
    image: saiamarendrareddy/job-posting-email-generator:${CLIENT_VERSION}
    container_name: saiamarendrareddy/job-posting-email-generator-client
    networks:
      - email-generator-network
    ports:
      - "${HOST_PORT}:8000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      OLLAMA_API_KEY: ${OLLAMA_API_KEY}
      MONGO_URI: ${MONGO_URI}

  # database service
  mongo:
    image: mongo:latest
    container_name: saiamarendrareddy/job-posting-email-generator-db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping').ok\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - email-generator-network
      - mongo-express-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  
  # mongo-express service
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mongo-express-network
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

# network configuration
networks:
  email-generator-network:
    driver: bridge
  mongo-express-network:
    driver: bridge